image: python:3.11

stages:
  - test
  - deploy

services:
  - name: mongo:7
    alias: mongo

variables:
  PYTHONPATH: $CI_PROJECT_DIR
  UV_CACHE_DIR: $CI_PROJECT_DIR/.uv

before_script:
  # Ensure ssh-agent is available and started
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval "$(ssh-agent -s)"

  # Prepare SSH key from GitLab CI file variable
  - mkdir -p ~/.ssh
  - echo "$GITHUB_SSH_KEY" > ~/.ssh/id_rsa
  - chmod 400 ~/.ssh/id_rsa
  - ssh-add ~/.ssh/id_rsa

  # Add GitHub to known hosts
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

  # Debug SSH agent
  - ssh-add -l || echo "âŒ No key loaded in ssh-agent"
  - ssh -T git@github.com || true

  # Python environment setup
  - python3 -m venv .venv
  - source .venv/bin/activate
  - pip install uv || pip install --upgrade pip && pip install uv
  - uv sync



test:
  stage: test
  script:
    - make test
  only:
    - main
    - merge_requests

deploy:
  stage: deploy
  script:
    - 'echo "ğŸš€ CI Deploy: make prod_deploy"'
    - make all ENV=PROD
  only:
    - main
