image: python:3.11

stages:
  - test
  - deploy

services:
  - name: mongo:7
    alias: mongo

variables:
  PYTHONPATH: $CI_PROJECT_DIR
  UV_CACHE_DIR: $CI_PROJECT_DIR/.uv

before_script:
  - eval "$(ssh-agent -s)"
  - mkdir -p ~/.ssh
  - echo "$GITHUB_SSH_KEY_B64" | base64 -d > ~/.ssh/id_rsa
  - chmod 400 ~/.ssh/id_rsa
  - echo "$GITHUB_SSH_KEY_B64" | base64 -d | head -n 5
  - echo "$GITHUB_SSH_KEY_B64" | base64 -d | ssh-keygen -lf - || echo "âŒ Broken key"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - ssh -T git@github.com || true
  - python3 -m venv .venv
  - source .venv/bin/activate
  - pip install uv || pip install --upgrade pip && pip install uv
  - uv sync

test:
  stage: test
  script:
    - make test
  only:
    - main
    - merge_requests

deploy:
  stage: deploy
  script:
    - 'echo "ðŸš€ CI Deploy: make prod_deploy"'
    - make all ENV=PROD
  only:
    - main
